/*******************************************************************************
**  DAVE App Name : IO001       App Version: 1.0.16               
**  This file is generated by DAVE, User modification to this file will be    **
**  overwritten at the next code generation.                                  **
*******************************************************************************/

/*CODE_BLOCK_BEGIN[IO001_Conf.h]*/
/******************************************************************************
 *
 * Copyright (C) 2014 Infineon Technologies AG. All rights reserved.
 *
 * Infineon Technologies AG (Infineon) is supplying this software for use with 
 * Infineon's microcontrollers.  
 * This file can be freely distributed within development tools that are 
 * supporting such microcontrollers. 
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED
 * OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.
 * INFINEON SHALL NOT, IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, 
 * OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
********************************************************************************
**                                                                            **
**                                                                            **
** PLATFORM : Infineon XMC4000/XMC1000 Series                                 **
**                                                                            **
** COMPILER : Compiler Independent                                            **
**                                                                            **
** AUTHOR   : App Developer                                                   **
**                                                                            **
** MAY BE CHANGED BY USER [yes/no]: Yes                                       **
**                                                                            **
** MODIFICATION DATE : Jan 20, 2014                                           **
**                                                                            **
**                                                                            **
*******************************************************************************/
/**
 * @file   IO001_Conf.h
 *
 * @brief  Configuration file generated based on UI settings 
 *         of IO001 App
 *
 */

#ifndef _CONF_IO001_H_
#define _CONF_IO001_H_

#ifdef __cplusplus
extern "C" {
#endif

/*******************************************************************************
@Defines
*******************************************************************************/

#include <DAVE3.h>


extern const IO001_HandleType IO001_Handle0;

extern const IO001_HandleType IO001_Handle1;

extern const IO001_HandleType IO001_Handle2;

extern const IO001_HandleType IO001_Handle3;

extern const IO001_HandleType IO001_Handle4;

extern const IO001_HandleType IO001_Handle5;

extern const IO001_HandleType IO001_Handle6;

extern const IO001_HandleType IO001_Handle7;

extern const IO001_HandleType IO001_Handle8;

extern const IO001_HandleType IO001_Handle9;


#ifdef __cplusplus
}
#endif
#endif  /* ifndef _CONF_IO001_H_ */
/*CODE_BLOCK_END*/

