language: generic
env:
  global:
    - CXX=g++-4.8
  matrix:
    - NODE_VERSION="5"
    - NODE_VERSION="4"
    - NODE_VERSION="4.3"
    - NODE_VERSION="4.2"
    - NODE_VERSION="4.1"
    - NODE_VERSION="4.0"
    - NODE_VERSION="0.12"
    - NODE_VERSION="0.11"
    - NODE_VERSION="0.10"
    - NODE_VERSION="iojs"  
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm;
    source /tmp/.nvm/nvm.sh;
    nvm install $NODE_VERSION;
    nvm use --delete-prefix $NODE_VERSION;
install:
  - npm install
script:
  - npm test